version: '3.9'
name: authentication-api

services:
  nest-api:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.nest.dev
    ports:
      - 3000:3000
    volumes:
      - ../.:/home/node/app
    networks:
      - app-network
    environment:
      # App
      - APP_PORT=3000
      - APP_ENV=development
      - APP_ALLOWED_ORIGINS=https://example.com/

      # Database
      - DATABASE_URL=postgresql://admin:admin123@db-postgresql-dev:5432/development

      # JWT
      - ACCESS_TOKEN_SECRET=access-token-secret
      - ACCESS_TOKEN_EXPIRES=15m
    depends_on:
      db-postgresql-dev:
        condition: service_healthy

  db-postgresql-dev:
    image: postgres:15.2-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: development
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network


networks:
  app-network:


volumes:
  db-data:
